// Regenerate TurboQuant KV quantizer parity goldens + generated constants
// table from the vendored vllm-metal Python reference.
// Explicit command, never automatic:  bun scripts/regen.ts turboquant
//
// Unlike the model-forward goldens (regen-kvq-goldens.ts et al.), this
// fixture is pure MLX math from fixed RNG keys — no model weights, no
// GPU-metallib-dependent SDPA dispatch — so it is machine-independent and
// always writes to the flat goldens/ set (same convention as
// goldens/tokenizer.json / goldens/chat-template.json), never a
// goldens/<machine-key>/ override.
//
// Shells out to lab/repro/vllm-metal-turboquant/gen_goldens.py under the
// oracle venv (mlx 0.31.2), which imports the vendored reference
// (turboquant_reference.py, see PROVENANCE.md) with a minimal vllm.logger
// shim. One adversarial golden (a constant-value input row) triggers the
// reference's genuine fp16 zero_point overflow to +-Infinity/NaN — the
// Python side encodes non-finite floats as the sentinel strings
// "Infinity"/"-Infinity"/"NaN" since JSON has no such literals; this script
// only round-trips them (JSON.stringify passes strings through unchanged),
// consumers of goldens/turboquant.json must parse those three strings back
// to +-Inf/NaN themselves. Writes:
//   goldens/turboquant.json       — sign vectors, Lloyd-Max tables, golden
//                                   K/V quantize/dequantize vectors
//   src/mlx/turboquant-tables.ts  — GENERATED constants (sign vectors +
//                                   Lloyd-Max centroid/boundary tables) for
//                                   the TS port to import directly, so the
//                                   TS side never re-derives them at runtime
//                                   and can only diverge from the oracle by
//                                   a bug in the encode/decode math itself.

import { ORACLE_PYTHON } from "../../tests/support/paths";

const REPRO_DIR = `${import.meta.dir}/../lab/repro/vllm-metal-turboquant`;
const GEN_SCRIPT = `${REPRO_DIR}/gen_goldens.py`;

// Leaf floats may be the sentinel strings "Infinity"/"-Infinity"/"NaN"
// (see the file header comment) — genuine non-finite reference outputs on
// the constant-value adversarial row, not a parse error.
type MaybeFinite = number | "Infinity" | "-Infinity" | "NaN";

interface GoldenVector {
  head_dim: number;
  config: string;
  k_quant_type: string;
  k_bits: number;
  v_bits: number;
  input_k: MaybeFinite[][][][];
  input_v: MaybeFinite[][][][];
  k_indices: number[][][][];
  k_scale: MaybeFinite[][][];
  k_zero: MaybeFinite[][][];
  k_packed: number[][][][];
  v_indices: number[][][][];
  v_packed: number[][][][];
  v_scale: MaybeFinite[][][];
  k_dequant: MaybeFinite[][][][];
  v_dequant: MaybeFinite[][][][];
}

interface GoldenOutput {
  signs: Record<string, number[]>;
  lloyd_max: Record<string, { centroids: number[]; boundaries: number[] }>;
  vectors: GoldenVector[];
}

const proc = Bun.spawn([ORACLE_PYTHON, GEN_SCRIPT], {
  stdout: "pipe",
  stderr: "pipe",
  cwd: REPRO_DIR,
});
const [out, err, code] = await Promise.all([
  new Response(proc.stdout).text(),
  new Response(proc.stderr).text(),
  proc.exited,
]);
if (code !== 0) throw new Error(`oracle failed (${code}):\n${err}`);

const golden = JSON.parse(out) as GoldenOutput;

await Bun.write("goldens/turboquant.json", JSON.stringify(golden, null, 1));
console.log("wrote goldens/turboquant.json");

// --- generated TS constants table ---

const HEAD_DIMS = [64, 128, 256, 512] as const;
const VALUE_BITS = [2, 3, 4, 5, 8] as const;

function fmtNumArray(nums: number[], perLine = 10): string {
  const lines: string[] = [];
  for (let i = 0; i < nums.length; i += perLine) {
    lines.push("  " + nums.slice(i, i + perLine).join(", ") + ",");
  }
  return lines.join("\n");
}

const signsEntries = HEAD_DIMS.map((d) => {
  const vals = golden.signs[String(d)];
  if (!vals || vals.length !== d) {
    throw new Error(`missing/mismatched sign vector for head_dim=${d}`);
  }
  return `  ${d}: [\n${fmtNumArray(vals)}\n  ],`;
}).join("\n");

const lloydMaxEntries = VALUE_BITS.map((bits) => {
  const entry = golden.lloyd_max[String(bits)];
  if (!entry) throw new Error(`missing Lloyd-Max table for bits=${bits}`);
  const want = 1 << bits;
  if (entry.centroids.length !== want || entry.boundaries.length !== want - 1) {
    throw new Error(
      `mismatched Lloyd-Max table shape for bits=${bits}: ` +
      `centroids=${entry.centroids.length} (want ${want}), ` +
      `boundaries=${entry.boundaries.length} (want ${want - 1})`,
    );
  }
  return `  ${bits}: {\n    centroids: [\n${fmtNumArray(entry.centroids)}\n    ],\n    boundaries: [\n${fmtNumArray(entry.boundaries)}\n    ],\n  },`;
}).join("\n");

const tsContent = `// GENERATED by scripts/regen.ts turboquant — DO NOT EDIT.
// Regenerate:  bun scripts/regen.ts turboquant
//
// Source: lab/repro/vllm-metal-turboquant/turboquant_reference.py (vendored
// vllm-metal oracle, see PROVENANCE.md in that directory), executed under
// the oracle venv (mlx 0.31.2) via gen_goldens.py.
//
// - SIGN_VECTORS[headDim]: the fwht() sign table (±1), derived from
//   mx.random.randint(0, 2, shape=(headDim,), key=mx.random.key(42)) —
//   deterministic across machines and spill/restore by construction.
// - LLOYD_MAX[bits]: Lloyd-Max (centroids, boundaries) for value
//   quantization at the given bit width. bits=3 is the vendored reference's
//   hardcoded fast-path table (CENTROIDS_3BIT/BOUNDARIES_3BIT); other widths
//   are the reference's own iterative Lloyd-Max fit on a unit-normal source
//   (mx.random.normal(key=mx.random.key(0)), 500 iterations), computed once
//   here and hardcoded — no runtime iteration in the TS port.

export const TURBOQUANT_HEAD_DIMS = [${HEAD_DIMS.join(", ")}] as const;
export type TurboQuantHeadDim = (typeof TURBOQUANT_HEAD_DIMS)[number];

export const SIGN_VECTORS: Record<TurboQuantHeadDim, number[]> = {
${signsEntries}
};

export const TURBOQUANT_VALUE_BITS = [${VALUE_BITS.join(", ")}] as const;
export type TurboQuantValueBits = (typeof TURBOQUANT_VALUE_BITS)[number];

export interface LloydMaxTable {
  centroids: number[];
  boundaries: number[];
}

export const LLOYD_MAX: Record<TurboQuantValueBits, LloydMaxTable> = {
${lloydMaxEntries}
};
`;

await Bun.write("src/mlx/turboquant-tables.ts", tsContent);
console.log("wrote src/mlx/turboquant-tables.ts");
