// Model-free unit tests for the universal rope factory + Phase-1.5 dense
// primitives. GPU-touching but tiny (no model weights, no downloads).
//
// Rope variants are checked BIT-EXACT against oracle-dumped fixtures
// (tests/fixtures/universal-rope/, generated by
// scripts/gen-universal-rope-fixtures.py in the oracle venv): frequency
// tables, pre-rope input scales (yarn mscale / su scale), and full rope
// outputs at two offsets, for default / linear / llama3 / yarn / longrope
// / traditional-partial. Skips cleanly if fixtures are absent.

import { describe, expect, test } from "bun:test";
import { existsSync } from "node:fs";
import { MlxArray } from "../src/mlx/array";
import { Dtype } from "../src/mlx/ffi";
import * as ops from "../src/mlx/ops";
import { QuantizedLinear } from "../src/model/gemma4-base";
import { DenseLinear, DenseEmbedding } from "../src/model/universal/modules";
import {
  initializeRope,
  UniversalRope,
  type RopeScalingConfig,
} from "../src/model/universal/rope";

const FIX = "tests/fixtures/universal-rope";
const haveFixtures = existsSync(`${FIX}/manifest.json`);

interface RopeCase {
  name: string;
  shape: number[];
  offsets?: number[];
  has_freqs?: boolean;
  scaling_config: RopeScalingConfig | null;
  dims?: number;
  base?: number;
  traditional?: boolean;
  max_position_embeddings?: number;
  mscale?: number;
  su_scale?: number;
  kind?: string;
}

async function f32(name: string): Promise<Float32Array> {
  return new Float32Array(await Bun.file(`${FIX}/${name}`).arrayBuffer());
}

function expectBitExact(ours: Float32Array, ref: Float32Array, label: string): void {
  expect(ours.length).toBe(ref.length);
  let maxDiff = 0;
  let diffs = 0;
  for (let i = 0; i < ref.length; i++) {
    const d = Math.abs(ours[i]! - ref[i]!);
    if (d > 0 || Number.isNaN(d)) diffs++;
    maxDiff = Math.max(maxDiff, d);
  }
  if (maxDiff !== 0) console.error(`${label}: ${diffs} diffs, max ${maxDiff}`);
  expect(maxDiff).toBe(0);
}

describe.skipIf(!haveFixtures)("universal rope vs oracle fixtures", async () => {
  if (!haveFixtures) return;
  const manifest = (await Bun.file(`${FIX}/manifest.json`).json()) as { cases: RopeCase[] };

  for (const c of manifest.cases.filter((c) => c.kind !== "gelu")) {
    test(`${c.name}: freqs + outputs bit-exact`, async () => {
      const rope: UniversalRope =
        c.name === "traditional-partial"
          ? new UniversalRope(c.dims!, true, c.base!, 1.0, null, 1, false)
          : initializeRope(
              c.dims!, c.base!, c.traditional ?? false, c.scaling_config,
              c.max_position_embeddings ?? null,
            );
      try {
        // frequency table (llama3/yarn/longrope)
        if (c.has_freqs) {
          expect(rope.freqs).not.toBeNull();
          expectBitExact(rope.freqs!.toFloat32(), await f32(`${c.name}-freqs.bin`), `${c.name} freqs`);
        }
        // pre-rope input scales (host float64 math — exact equality)
        if (c.mscale !== undefined) expect(rope.preScale).toBe(c.mscale);
        if (c.su_scale !== undefined) {
          expect(rope.preScale).toBe(c.su_scale);
          expect(rope.preScaleAlways).toBe(true);
        }
        // full rope outputs at each offset, on bf16 inputs like the models
        const inF32 = await f32(`${c.name}-input.bin`);
        const in32 = MlxArray.fromFloat32(inF32, c.shape);
        const x = in32.astype(Dtype.bfloat16);
        in32.dispose();
        for (const off of c.offsets!) {
          const out = rope.apply(x, off);
          expectBitExact(out.toFloat32(), await f32(`${c.name}-out${off}.bin`), `${c.name} out@${off}`);
          out.dispose();
        }
        x.dispose();
      } finally {
        rope.dispose();
      }
    });
  }

  test("geluPrecise (erf) bit-exact vs nn.gelu", async () => {
    const c = manifest.cases.find((c) => c.kind === "gelu")!;
    const in32 = MlxArray.fromFloat32(await f32("gelu-input.bin"), c.shape);
    const x = in32.astype(Dtype.bfloat16);
    in32.dispose();
    const out = ops.geluPrecise(x);
    expectBitExact(out.toFloat32(), await f32("gelu-out.bin"), "gelu");
    out.dispose();
    x.dispose();
  });
});

describe("dense primitives (Phase 1.5)", () => {
  test("DenseLinear: x @ W.T (+ addmm bias) matches manual composition", () => {
    // Small integer-valued f32 tensors ⇒ exact arithmetic.
    const w = MlxArray.fromFloat32(new Float32Array([1, 2, 3, 4, 5, 6]), [2, 3]); // [out=2, in=3]
    const bias = MlxArray.fromFloat32(new Float32Array([10, -20]), [2]);
    const x = MlxArray.fromFloat32(new Float32Array([1, -1, 2, 0, 3, -2]), [2, 3]);

    const lin = new DenseLinear(w, bias);
    expect(lin.inFeatures).toBe(3);
    expect(lin.outFeatures).toBe(2);
    const out = lin.forward(x);
    // row0: [1,-1,2]·[1,2,3]+10 = 5+10, [1,-1,2]·[4,5,6]-20 = 11-20
    // row1: [0,3,-2]·[1,2,3]+10 = 0+10? (6-6)=0 → 10, [0,3,-2]·[4,5,6] = 3 → -17
    expect([...out.toFloat32()]).toEqual([15, -9, 10, -17]);

    const noBias = new DenseLinear(w, null);
    const out2 = noBias.forward(x);
    expect([...out2.toFloat32()]).toEqual([5, 11, 0, 3]);
    for (const a of [out, out2, x, bias, w]) a.dispose();
  });

  test("DenseEmbedding: encode gathers rows; asLinear is x @ W.T", () => {
    const w = MlxArray.fromFloat32(new Float32Array([1, 2, 3, 4, 5, 6]), [3, 2]);
    const emb = new DenseEmbedding(w);
    const ids = ops.fromInt32([2, 0], [1, 2]);
    const rows = emb.encode(ids);
    expect([...rows.toFloat32()]).toEqual([5, 6, 1, 2]);
    const h = MlxArray.fromFloat32(new Float32Array([1, -1]), [1, 2]);
    const logits = emb.asLinear(h);
    expect([...logits.toFloat32()]).toEqual([-1, -1, -1]);
    for (const a of [rows, ids, h, logits, w]) a.dispose();
  });

  test("QuantizedLinear additive .bias applies after the matmul", () => {
    // Quantize a small weight and check bias-in-forward == manual add.
    const wVals = new Float32Array(4 * 64);
    for (let i = 0; i < wVals.length; i++) wVals[i] = ((i * 37) % 13) - 6;
    const w = MlxArray.fromFloat32(wVals, [4, 64]);
    const q = ops.quantize(w, 64, 4);
    const spec = { bits: 4, groupSize: 64, mode: "affine" };
    const bias = MlxArray.fromFloat32(new Float32Array([1, -2, 3, -4]), [4]);
    const xVals = new Float32Array(64);
    for (let i = 0; i < 64; i++) xVals[i] = (i % 5) - 2;
    const x = MlxArray.fromFloat32(xVals, [1, 64]);

    const withBias = new QuantizedLinear(q.packed, q.scales, q.biases, spec, bias);
    const noBias = new QuantizedLinear(q.packed, q.scales, q.biases, spec);
    const a = withBias.forward(x);
    const b0 = noBias.forward(x);
    const b = ops.add(b0, bias);
    expect([...a.toFloat32()]).toEqual([...b.toFloat32()]);
    for (const arr of [a, b0, b, x, bias, w, q.packed, q.scales, q.biases]) arr.dispose();
  });
});
