// mlx-bun memory — "The Dreaming" synthesis store (bun:sqlite).
//
// Two kinds of tables live here:
//
//   • DERIVED CACHE — entities, entity_aliases, categories, article_categories,
//     infobox_facts, links. These are a *cache of the markdown vault*: every row
//     can be regenerated by reindexing the articles. reindex makes them match the
//     vault, NEVER the reverse — if a row disagrees with the markdown, the
//     markdown wins and the row is rebuilt.
//
//   • SYNTHESIS LEDGER — messages, chunks, chunk_entities, chunk_sections,
//     synthesized_chunk_sections, watermarks (+ buckets/chunk_buckets +
//     subject_redirects, the fold/capture sub-concept→home-article edges that the
//     reindex projects into entity_aliases). These are
//     the pipeline's bookkeeping: what we ingested, how we cut it, and what has
//     already been folded into the vault. This is the authoritative record of
//     pipeline progress and is not reconstructable from the vault alone.
//
// Storage is pointer-based: chunks do NOT copy conversation text. A chunk is a
// [start,end] position range into its conversation's messages; chunkText()
// reassembles the slice on demand. Total stored text == the messages, once.
//
// Reuses mlx-bun's per-domain sqlite pattern (cf. JobStore in src/jobs/db.ts,
// EvalDB in src/evaldb.ts): a small class over bun:sqlite with WAL +
// schema-in-constructor + a migrate() hook, living under ~/.cache/mlx-bun/.
// It's rebuildable derived state, so it belongs in the cache, NOT the vault.

import { Database } from "bun:sqlite";
import { mkdirSync } from "node:fs";

export const DEFAULT_MEMORY_DB = `${process.env.HOME}/.cache/mlx-bun/memory.sqlite`;

export interface ConversationRow {
  /** Stable conv id: first 8 hex of the session UUID (the conv:HASH citation). */
  conv: string;
  source: string; // "pi-web" | "pi-terminal"
  title: string;
  updated_at: number;
  chunked_at: number | null;
}

export interface ChunkRow {
  /** Deterministic id `${conv}:${start}-${end}` — idempotent re-chunking. */
  id: string;
  conv: string;
  start: number;
  end: number;
  label: string | null;
}

export interface EntityRow {
  name: string;
  article_stem: string | null;
  kind: string | null;
  notable: number;
}

export interface BucketRow {
  name: string;
  article_stem: string;
  description: string;
}

/** Deterministic chunk id from its conversation + position range. */
export function chunkId(conv: string, start: number, end: number): string {
  return `${conv}:${start}-${end}`;
}

const SCHEMA = `
CREATE TABLE IF NOT EXISTS conversations (
  conv       TEXT PRIMARY KEY,
  source     TEXT,
  title      TEXT DEFAULT '',
  updated_at INTEGER,
  chunked_at INTEGER
);
CREATE TABLE IF NOT EXISTS messages (
  conv     TEXT REFERENCES conversations(conv) ON DELETE CASCADE,
  position INTEGER,
  role     TEXT,
  uuid     TEXT,
  text     TEXT,
  PRIMARY KEY (conv, position)
);
CREATE TABLE IF NOT EXISTS chunks (
  id    TEXT PRIMARY KEY,
  conv  TEXT REFERENCES conversations(conv) ON DELETE CASCADE,
  start INTEGER,
  end   INTEGER,
  label TEXT
);
CREATE INDEX IF NOT EXISTS idx_chunks_conv ON chunks(conv);
CREATE TABLE IF NOT EXISTS entities (
  name         TEXT PRIMARY KEY,
  article_stem TEXT,
  kind         TEXT,
  notable      INTEGER DEFAULT 0
);
CREATE TABLE IF NOT EXISTS entity_aliases (
  alias       TEXT,
  entity_name TEXT REFERENCES entities(name) ON DELETE CASCADE,
  PRIMARY KEY (alias, entity_name)
);
CREATE INDEX IF NOT EXISTS idx_aliases_alias ON entity_aliases(alias);
CREATE TABLE IF NOT EXISTS chunk_entities (
  chunk_id     TEXT REFERENCES chunks(id) ON DELETE CASCADE,
  entity_name  TEXT REFERENCES entities(name) ON DELETE CASCADE,
  surface_form TEXT,
  PRIMARY KEY (chunk_id, entity_name)
);
CREATE TABLE IF NOT EXISTS categories (
  name       TEXT PRIMARY KEY,
  definition TEXT DEFAULT '',
  parent     TEXT REFERENCES categories(name) ON DELETE SET NULL
);
CREATE TABLE IF NOT EXISTS article_categories (
  article_stem TEXT,
  category     TEXT REFERENCES categories(name) ON DELETE CASCADE,
  source       TEXT,
  PRIMARY KEY (article_stem, category)
);
CREATE INDEX IF NOT EXISTS idx_artcat_category ON article_categories(category);
CREATE TABLE IF NOT EXISTS infobox_facts (
  article_stem TEXT,
  key          TEXT,
  value        TEXT,
  kind         TEXT,
  entity_link  TEXT,
  PRIMARY KEY (article_stem, key, value)
);
CREATE INDEX IF NOT EXISTS idx_infobox_key ON infobox_facts(key);
CREATE INDEX IF NOT EXISTS idx_infobox_link ON infobox_facts(entity_link);
CREATE TABLE IF NOT EXISTS links (
  src_stem TEXT,
  dst_stem TEXT,
  via      TEXT,
  PRIMARY KEY (src_stem, dst_stem, via)
);
CREATE INDEX IF NOT EXISTS idx_links_dst ON links(dst_stem);
CREATE TABLE IF NOT EXISTS chunk_sections (
  chunk_id       TEXT REFERENCES chunks(id) ON DELETE CASCADE,
  article_stem   TEXT,
  section_anchor TEXT,
  PRIMARY KEY (chunk_id, article_stem, section_anchor)
);
CREATE TABLE IF NOT EXISTS synthesized_chunk_sections (
  chunk_id       TEXT REFERENCES chunks(id) ON DELETE CASCADE,
  article_stem   TEXT,
  section_anchor TEXT,
  synthesized_at INTEGER,
  PRIMARY KEY (chunk_id, article_stem, section_anchor)
);
CREATE TABLE IF NOT EXISTS reconciled_articles (
  article_stem  TEXT,
  reconciled_at INTEGER,
  refreshed     TEXT,
  rewritten     TEXT,
  PRIMARY KEY (article_stem, reconciled_at)
);
CREATE TABLE IF NOT EXISTS watermarks (
  source     TEXT PRIMARY KEY,
  cursor     TEXT,
  updated_at INTEGER
);
CREATE TABLE IF NOT EXISTS buckets (
  name         TEXT PRIMARY KEY,
  article_stem TEXT,
  description  TEXT DEFAULT ''
);
CREATE TABLE IF NOT EXISTS chunk_buckets (
  chunk_id TEXT REFERENCES chunks(id) ON DELETE CASCADE,
  bucket   TEXT REFERENCES buckets(name) ON DELETE CASCADE,
  PRIMARY KEY (chunk_id, bucket)
);
CREATE TABLE IF NOT EXISTS subject_redirects (
  surface     TEXT,
  target_stem TEXT,
  kind        TEXT,
  PRIMARY KEY (surface, target_stem)
);
CREATE INDEX IF NOT EXISTS idx_redirect_target ON subject_redirects(target_stem);
`;

/**
 * "The Dreaming" synthesis store. Same shape as JobStore/EvalDB: open in the
 * constructor (WAL on, foreign keys on, schema ensured, additive migrate),
 * expose `db`, and a `close()`.
 */
export class MemoryStore {
  readonly db: Database;
  readonly dbPath: string;

  constructor(dbPath: string = DEFAULT_MEMORY_DB) {
    if (dbPath !== ":memory:") {
      try { mkdirSync(dbPath.slice(0, dbPath.lastIndexOf("/")), { recursive: true }); } catch {}
    }
    this.dbPath = dbPath;
    this.db = new Database(dbPath);
    this.db.exec("PRAGMA journal_mode = WAL");
    if (this.hasLegacySchema()) this.dropAllTables();
    this.db.exec("PRAGMA foreign_keys = ON");
    this.db.exec(SCHEMA);
    this.migrate();
  }

  /**
   * A DB written by the pre-rewrite (bucket/transcript) schema. There is no
   * production data to preserve, so detecting either marker means: nuke and
   * recreate from scratch. Markers: chunks.text column, or the dropped
   * synthesized_bucket_chunks table.
   */
  private hasLegacySchema(): boolean {
    const cols = this.db.query("PRAGMA table_info(chunks)").all() as { name: string }[];
    if (cols.some((c) => c.name === "text")) return true;
    const legacy = this.db
      .query("SELECT name FROM sqlite_master WHERE type='table' AND name='synthesized_bucket_chunks'")
      .get();
    return legacy != null;
  }

  /** Drop every user table (FK checks off during the teardown). */
  private dropAllTables(): void {
    this.db.exec("PRAGMA foreign_keys = OFF");
    const tables = this.db
      .query("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
      .all() as { name: string }[];
    for (const { name } of tables) this.db.exec(`DROP TABLE IF EXISTS "${name}"`);
  }

  /** Additive-only migrations (mirrors JobStore.migrate). Re-opening is a no-op. */
  private migrate(): void {
    // No columns to add today; the hook stays so future fields are additive.
  }

  /**
   * Reassemble a chunk's text from its messages by position range — chunks are
   * pointers, not copies. Returns "" for an unknown chunk id.
   */
  chunkText(id: string): string {
    const chunk = this.db
      .query("SELECT conv, start, end FROM chunks WHERE id = ?")
      .get(id) as { conv: string; start: number; end: number } | null;
    if (!chunk) return "";
    const rows = this.db
      .query("SELECT text FROM messages WHERE conv = ? AND position BETWEEN ? AND ? ORDER BY position")
      .all(chunk.conv, chunk.start, chunk.end) as { text: string }[];
    return rows.map((r) => r.text).join("\n");
  }

  close(): void {
    this.db.close();
  }
}
