#!/usr/bin/env bun
// Hygiene gate — the "mess can't re-form" guarantee.
//
// Two checks, both must pass:
//
//   1. binaries   — no tracked file may be a binary artifact (or >1 MB of
//                   anything) unless it is on an EXPLICIT, size-capped
//                   allowlist with a recorded rationale. This is the direct
//                   guardrail against a repeat of the goldens episode
//                   (179 MB .git driven by 497 machine-specific .bin blobs
//                   that regenerated on every run). Allowlisted entries are
//                   the exception, not the rule: adding one requires a
//                   justification and a regen path.
//
//   2. docs-map   — every docs/**/*.md must appear (by basename) in the
//                   CLAUDE.md "Doc map" section, so the hand-maintained map
//                   can't silently drift from reality.
//
// Usage:
//   bun scripts/check-hygiene.ts            # check all tracked files (CI)
//   bun scripts/check-hygiene.ts --staged   # check only staged files (pre-commit)
//   bun scripts/check-hygiene.ts --binaries # just the binary gate
//   bun scripts/check-hygiene.ts --docs-map # just the docs-map assertion
//
// Wire into CI via scripts/test.sh; for pre-commit, run with --staged.

import { readFileSync } from "node:fs";
import { execSync } from "node:child_process";

const ROOT = import.meta.dir + "/..";
const ONE_MB = 1_048_576;

type Mode = "all" | "staged" | "binaries" | "docs-map";
const args = new Set(process.argv.slice(2));
const mode: Mode = args.has("--staged")
  ? "staged"
  : args.has("--binaries")
    ? "binaries"
    : args.has("--docs-map")
      ? "docs-map"
      : "all";

// ---------------------------------------------------------------------------
// 1. Binary-in-git gate
// ---------------------------------------------------------------------------

interface AllowEntry {
  /** gitignore-style glob matched against the repo-relative path. */
  glob: string;
  /** Max bytes; a matching file over this FAILs. */
  maxBytes: number;
  why: string;
}

// The explicit allowlist. Every entry is a deliberate, documented exception
// to the "no binaries in git" rule. To add one: justify why it can't be
// untracked (e.g. no bit-exact regen, or CI-load-bearing + tiny) and confirm
// it is NOT a churning machine-specific artifact — those belong under a
// regen script + gitignore, like goldens/**.bin.
const ALLOW: AllowEntry[] = [
  {
    glob: "fixtures/adapters/*/adapters.safetensors",
    maxBytes: 7_000_000,
    why: "Stable one-time-trained LoRA adapter INPUTS for the opt-in MLX_BUN_TEST_LORA hot-swap test (also requires the e4b base). Trained once (2026-06-10); not churning. Reproducible from tracked data + adapter_config.json; the bit-exact regen trainer-of-record is TBD with Josh (see docs/design/repo-cleanup-plan.md B2).",
  },
  {
    glob: "tests/fixtures/qwen-delta-golden.json",
    maxBytes: 1_200_000,
    why: "Text JSON golden (bf16-quantized reference kernel output). Model-free CI load-bearer (tests/qwen-delta.test.ts, no model load). Regenerated by scripts/gen-qwen-delta-golden.py.",
  },
  {
    glob: "tests/fixtures/**/*.bin",
    maxBytes: 16_384,
    why: "Model-free universal-rope bit-exact oracle fixtures (4–8 KB each). CI load-bearer; tests/universal-rope.test.ts skips cleanly if absent. Regenerated by scripts/gen-universal-rope-fixtures.py.",
  },
  {
    glob: "lab/**/lib*.dylib",
    maxBytes: 102_400,
    why: "Compiled C dylibs for the bun-ffi-f64 upstream-bug repro (lab/repro/). Rebuilt from tracked .c sources; tiny (≤36 KB).",
  },
];

const BINARY_EXT = /\.(bin|safetensors|dylib|gguf|metallib)$/i;

// Minimal glob → RegExp: supports *, **, and literal segments.
function globToRe(glob: string): RegExp {
  // Anchor and escape, then translate *, **  (handle **/ and /** and /**/).
  let re = "";
  let i = 0;
  while (i < glob.length) {
    const c = glob[i]!;
    if (c === "*") {
      if (glob[i + 1] === "*") {
        // **
        i += 2;
        // consume a following slash — **/ means "any number of dirs"
        if (glob[i] === "/") {
          i += 1;
          re += "(?:.*/)?";
        } else {
          re += ".*";
        }
      } else {
        i += 1;
        re += "[^/]*";
      }
    } else if (".+?^${}()|[]\\".includes(c)) {
      re += "\\" + c;
      i += 1;
    } else {
      re += c;
      i += 1;
    }
  }
  return new RegExp("^" + re + "$");
}

const ALLOW_RE = ALLOW.map((a) => ({ ...a, re: globToRe(a.glob) }));

function allowMatch(path: string): AllowEntry | null {
  return ALLOW_RE.find((a) => a.re.test(path)) ?? null;
}

function listFiles(): string[] {
  const cmd =
    mode === "staged"
      ? "git diff --cached --name-only --diff-filter=A"
      : "git ls-files";
  return execSync(cmd, { cwd: ROOT, encoding: "utf8" })
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);
}

function fileBytes(path: string): number {
  // Use git-cat-file for accuracy against the index/HEAD (avoids stat on
  // possibly-deleted working-tree files during --staged).
  try {
    const out = execSync(`git cat-file -s :${path}`, {
      cwd: ROOT,
      encoding: "utf8",
    });
    return parseInt(out.trim(), 10);
  } catch {
    // Not in index (e.g. working-tree-only); fall back to fs.
    try {
      return readFileSync(`${ROOT}/${path}`).length;
    } catch {
      return 0;
    }
  }
}

function checkBinaries(): string[] {
  const files = listFiles();
  const fails: string[] = [];
  for (const f of files) {
    const isBinary = BINARY_EXT.test(f);
    let size: number;
    try {
      size = fileBytes(f);
    } catch {
      continue; // vanished; not our concern here
    }
    const isLarge = size > ONE_MB;
    if (!isBinary && !isLarge) continue;

    const entry = allowMatch(f);
    if (!entry) {
      fails.push(
        `  FAIL  ${f} (${(size / ONE_MB).toFixed(2)} MB${isBinary ? ", binary ext" : ""}) — NOT on the allowlist. If it's a regenerable artifact, untrack + gitignore + add a regen script (see goldens/README.md policy). Otherwise add a justified entry to ALLOW in scripts/check-hygiene.ts.`,
      );
    } else if (size > entry.maxBytes) {
      fails.push(
        `  FAIL  ${f} (${size} B) — allowlisted (${entry.glob}, cap ${entry.maxBytes} B) but EXCEEDS the cap. ${entry.why}`,
      );
    }
  }
  return fails;
}

// ---------------------------------------------------------------------------
// 2. docs-map coverage assertion
// ---------------------------------------------------------------------------

function checkDocsMap(): string[] {
  const claude = readFileSync(`${ROOT}/CLAUDE.md`, "utf8");
  // Isolate the Doc map section (from "**Doc map:**" up to the next "**" header).
  const start = claude.indexOf("**Doc map:**");
  if (start < 0) return ["  FAIL  CLAUDE.md has no '**Doc map:**' section."];
  const rest = claude.slice(start);
  const nextHdr = rest.indexOf("\n**", 1);
  const mapSection = nextHdr > 0 ? rest.slice(0, nextHdr) : rest;

  // Enumerate every tracked docs/**/*.md (exclude docs/archive/ frozen HTML
  // neighbors and dotfiles; .md only).
  const docs = execSync("git ls-files 'docs/*.md' 'docs/**/*.md'", {
    cwd: ROOT,
    encoding: "utf8",
  })
    .split("\n")
    .map((s) => s.trim())
    .filter(Boolean);

  const missing: string[] = [];
  for (const f of docs) {
    const base = f.replace(/.*\//, "").replace(/\.md$/, "");
    if (!mapSection.includes(base)) missing.push(f);
  }
  // Spurious: files in the map that no longer exist (best-effort, warn only).
  return missing.map(
    (f) =>
      `  FAIL  ${f} — not mentioned in CLAUDE.md Doc map (by basename). Add it to the relevant docs/{reference,design,investigations,planning}/ bullet.`,
  );
}

// ---------------------------------------------------------------------------
// run
// ---------------------------------------------------------------------------

let exit = 0;
const runBin = mode === "all" || mode === "staged" || mode === "binaries";
const runMap = mode === "all" || mode === "docs-map";

if (runBin) {
  const fails = checkBinaries();
  console.log(`== hygiene: binaries (${mode}) ==`);
  if (fails.length) {
    fails.forEach((l) => console.log(l));
    console.log(`  ${fails.length} binary/huge-file violation(s).`);
    exit = 1;
  } else {
    console.log("  OK — every binary/large tracked file is allowlisted + in-cap.");
  }
}
if (runMap) {
  const fails = checkDocsMap();
  console.log(`== hygiene: docs-map coverage ==`);
  if (fails.length) {
    fails.forEach((l) => console.log(l));
    console.log(`  ${fails.length} doc(s) missing from the map.`);
    exit = 1;
  } else {
    console.log("  OK — every docs/**/*.md appears in the CLAUDE.md Doc map.");
  }
}
process.exit(exit);
