// Renders the A/B/C sample JSON (scripts/hlg-ab.ts) into a side-by-side HTML viewer.
//   bun scripts/hlg-ab-html.ts   →   docs/investigations/hlg-ab.html

import { readFileSync, writeFileSync } from "node:fs";

type AB = {
  model: string; n: number;
  configs: { id: string; label: string; desc: string }[];
  prompts: { tag: string; text: string; samples: Record<string, string[]> }[];
};
const data = JSON.parse(readFileSync(`${process.cwd()}/docs/investigations/hlg-runs/hlg-ab.json`, "utf8")) as AB;
const COLORS: Record<string, string> = { A: "#64748b", B: "#2563eb", C: "#0891b2" };
const esc = (s: string): string => s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");

const CSS = `
:root{--text:#1f2937;--text2:#475569;--text3:#94a3b8;--bg:#f7f9fc;--card:#fff;--bd:#e2e8f0;--grid:#f1f5f9}
*{box-sizing:border-box}
body{margin:0;background:var(--bg);color:var(--text);font:15px/1.6 -apple-system,BlinkMacSystemFont,"Segoe UI",ui-sans-serif,system-ui,sans-serif;-webkit-font-smoothing:antialiased}
.wrap{max-width:1240px;margin:0 auto;padding:34px 22px 100px}
h1{font-size:25px;margin:0 0 3px;letter-spacing:-.02em}
.sub{color:var(--text2);font-size:14.5px;max-width:780px;margin:0 0 8px}
.legend{display:flex;flex-wrap:wrap;gap:14px;margin:14px 0 26px;font-size:13px}
.legend .c{display:flex;gap:8px;align-items:baseline;background:var(--card);border:1px solid var(--bd);border-radius:10px;padding:8px 13px}
.legend .dot{width:10px;height:10px;border-radius:3px;flex:none;position:relative;top:1px}
.legend b{font-weight:700}.legend .d{color:var(--text3);font-size:12px}
.card{background:var(--card);border:1px solid var(--bd);border-radius:14px;padding:18px 20px;margin:0 0 20px;box-shadow:0 1px 2px rgba(15,23,42,.04),0 10px 30px -24px rgba(15,23,42,.2)}
.q{font-size:12px;text-transform:uppercase;letter-spacing:.06em;color:var(--text3);font-weight:700}
.qt{font-size:16px;font-weight:600;margin:3px 0 16px}
.cols{display:grid;grid-template-columns:repeat(3,1fr);gap:16px}
@media(max-width:900px){.cols{grid-template-columns:1fr}}
.col h3{font-size:13px;margin:0 0 9px;display:flex;align-items:center;gap:8px}
.col h3 .dot{width:9px;height:9px;border-radius:3px}
.col h3 .d{font-weight:400;color:var(--text3);font-size:11.5px}
.samp{font-size:13.5px;color:#0f172a;background:var(--grid);border-radius:9px;padding:9px 11px;margin:0 0 8px;border-left:3px solid transparent}
.samp .n{color:var(--text3);font-weight:700;font-size:11px;margin-right:6px}
.note{font-size:13px;color:var(--text3);margin-top:28px;border-top:1px solid var(--bd);padding-top:14px}
`;

let cards = "";
for (const p of data.prompts) {
  let cols = "";
  for (const c of data.configs) {
    const col = COLORS[c.id] ?? "#64748b";
    const samples = (p.samples[c.id] ?? []).map((s, i) =>
      `<div class="samp" style="border-left-color:${col}"><span class="n">${i + 1}</span>${esc(s)}</div>`).join("");
    cols += `<div class="col"><h3><span class="dot" style="background:${col}"></span>${c.label}<span class="d">${c.id}</span></h3>${samples}</div>`;
  }
  cards += `<div class="card"><div class="q">${p.tag}</div><div class="qt">${esc(p.text)}</div><div class="cols">${cols}</div></div>`;
}

const legend = data.configs.map((c) =>
  `<div class="c"><span class="dot" style="background:${COLORS[c.id]}"></span><div><b>${c.label}</b> &nbsp;<span class="d">${esc(c.desc)}</span></div></div>`).join("");

const html = `<!doctype html><html lang="en"><head><meta charset="utf-8">
<meta name="viewport" content="width=device-width,initial-scale=1"><title>HLG A/B samples</title><style>${CSS}</style></head>
<body><div class="wrap">
<h1>HLG sampling — side-by-side samples</h1>
<p class="sub">The same prompts, sampled three ways on <b>${esc(data.model)}</b> (${data.n} samples each, fixed seeds). Only the
sampling method changes. Read down a column to feel each sampler's character; read across to compare on one prompt.</p>
<div class="legend">${legend}</div>
${cards}
<p class="note">Generated by <code>scripts/hlg-ab.ts</code> → <code>scripts/hlg-ab-html.ts</code>. Notice how <b>HLG base</b> tends to
converge on a single strong continuation (lower diversity — the tight shoulder concentrates on the high-probability path), while
<b>HLG loose-A</b> spreads out — the same behavior the diversity sweeps measured, here in plain text.</p>
</div></body></html>`;

const outPath = `${process.cwd()}/docs/investigations/hlg-ab.html`;
writeFileSync(outPath, html);
console.log(`wrote ${outPath} (${(html.length / 1024).toFixed(0)} KB)`);
