// mlx-bun harness pi — register mlx-bun as a provider in the user's pi
// install (Phase 16 P1, docs/investigations/pi-builtin-investigation.md).
//
// Mechanism: a generated extension file in ~/.pi/agent/extensions/ that
// calls pi.registerProvider() with dynamic discovery — it fetches
// /v1/models from the running server at pi startup so the model list
// tracks the server, and falls back to the list baked at install time
// when the server is down. No models.json surgery; reversible by
// deleting the one file (or `mlx-bun harness pi --remove`).

import { existsSync, mkdirSync, readFileSync, realpathSync, rmSync, writeFileSync } from "node:fs";
import { homedir } from "node:os";
import { dirname, join } from "node:path";

export const PI_EXTENSION_FILENAME = "mlx-bun-provider.ts";
export const PI_PROVIDER_ID = "mlx-bun";
/** Stable pi-facing model id. The server runs exactly one model at a time
 *  (memory: the 26B alone is 18 GB) and which one varies run-to-run, so
 *  advertising the real, changing repo id makes pi's persisted default go
 *  stale ("No models match …"). A fixed id resolves to whatever single
 *  model is loaded; the real model is carried in the `name` field, and the
 *  server still reports the true id in /v1/models and responses. Gives a
 *  clean `mlx-bun/local` handle instead of `mlx-bun/mlx-community/…`. */
export const PI_LOCAL_MODEL_ID = "local";
// 127.0.0.1 (the server's actual default bind), not "localhost": the generated
// extension runs under the USER'S pi (node/jiti, not Bun), so don't depend on
// how that runtime's resolver maps localhost.
export const DEFAULT_BASE_URL = "http://127.0.0.1:8080/v1";

export function defaultPiExtensionsDir(): string {
  return join(homedir(), ".pi", "agent", "extensions");
}

export interface PiDetection {
  found: boolean;
  binPath?: string;
  version?: string;
}

/** Locate the user's pi install without spawning it (the bin shim may
 *  resolve to a node too old for pi-tui's /v-flag regexes). */
export function detectPi(): PiDetection {
  const candidates = [Bun.which("pi"), join(homedir(), ".bun", "bin", "pi")]
    .filter((p): p is string => !!p && existsSync(p));
  for (const bin of candidates) {
    let version: string | undefined;
    try {
      // bin -> .../node_modules/@earendil-works/pi-coding-agent/dist/cli.js
      let dir = dirname(realpathSync(bin));
      for (let i = 0; i < 4 && dir !== "/"; i++, dir = dirname(dir)) {
        const pkg = join(dir, "package.json");
        if (existsSync(pkg)) {
          const meta = JSON.parse(readFileSync(pkg, "utf8")) as { name?: string; version?: string };
          if (meta.name === "@earendil-works/pi-coding-agent") version = meta.version;
          break;
        }
      }
    } catch {}
    return { found: true, binPath: bin, version };
  }
  return { found: false };
}

export interface ServerModel {
  id: string;
  contextWindow: number;
  maxTokens: number;
  reasoning: boolean;
  vision: boolean;
}

/** Discover the SERVED model from a running mlx-bun server; [] when
 *  unreachable. /v1/models lists the served model first (the only row
 *  carrying the capability extras: context_window/reasoning/vision) and then
 *  every other servable model in the registry — those are things `mlx-bun
 *  serve` COULD run, not models this server answers for, so they must not be
 *  registered with pi. */
export async function fetchServerModels(baseUrl: string, timeoutMs = 3000): Promise<ServerModel[]> {
  try {
    const res = await fetch(`${baseUrl.replace(/\/$/, "")}/models`, {
      signal: AbortSignal.timeout(timeoutMs),
    });
    if (!res.ok) return [];
    const body = (await res.json()) as {
      data?: Array<{ id: string; context_window?: number; reasoning?: boolean; vision?: boolean }>;
    };
    const rows = body.data ?? [];
    const served = rows.find((m) => m.context_window !== undefined) ?? rows[0];
    if (!served) return [];
    return [{
      id: served.id,
      contextWindow: served.context_window ?? 32768,
      maxTokens: 8192,
      reasoning: !!served.reasoning,
      vision: !!served.vision,
    }];
  } catch {
    return [];
  }
}

/** GET /v1/models with a short timeout; null when no server is up. The
 *  `mlx-bun pi` and `serve` commands use this to decide reuse-vs-start. */
export async function probeServer(baseUrl: string, timeoutMs = 1500): Promise<ServerModel[] | null> {
  const models = await fetchServerModels(baseUrl, timeoutMs);
  return models.length > 0 ? models : null;
}

/** Render the pi extension source. Plain self-contained TS — pi loads it
 *  with jiti, so no imports and no dependency on pi's type packages. */
export function renderPiExtension(baseUrl: string, fallbackModels: ServerModel[]): string {
  const fallback = JSON.stringify(
    fallbackModels.map((m) => modelEntry(m)),
    null,
    2,
  );
  return `// Generated by \`mlx-bun harness pi\` — safe to delete.
// Registers the local mlx-bun server as a pi provider. Models are
// discovered live from the server at pi startup; the baked list below
// is the fallback when the server isn't running.
const BASE_URL = ${JSON.stringify(baseUrl)};
const FALLBACK_MODELS = ${fallback};

export default async function (pi: any) {
  let models = FALLBACK_MODELS;
  try {
    const res = await fetch(\`\${BASE_URL}/models\`, { signal: AbortSignal.timeout(2000) });
    if (res.ok) {
      const { data } = await res.json();
      if (Array.isArray(data) && data.length > 0) {
        // The SERVED model is the row with the capability extras (first);
        // the rest are servable-but-not-served registry entries.
        const served = data.find((m: any) => m.context_window !== undefined) ?? data[0];
        models = [{
          id: ${JSON.stringify(PI_LOCAL_MODEL_ID)},
          name: \`\${served.id} (mlx-bun local)\`,
          reasoning: !!served.reasoning,
          compat: {
            supportsDeveloperRole: false,
            ...(served.reasoning ? { thinkingFormat: "qwen-chat-template" } : {}),
          },
          input: served.vision ? ["text", "image"] : ["text"],
          cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
          contextWindow: served.context_window ?? 32768,
          maxTokens: 8192,
        }];
      }
    }
  } catch {}
  if (models.length === 0) return; // nothing to register
  pi.registerProvider(${JSON.stringify(PI_PROVIDER_ID)}, {
    baseUrl: BASE_URL,
    apiKey: "sk-mlx-bun-local",
    api: "openai-completions",
    models,
  });
}
`;
}

function modelEntry(m: ServerModel) {
  return {
    id: PI_LOCAL_MODEL_ID,
    name: `${m.id} (mlx-bun local)`,
    reasoning: !!m.reasoning,
    // Kept aligned with buildPiProvider (src/pi-provider.ts): the system
    // prompt must arrive as `system`, not `developer`.
    compat: {
      supportsDeveloperRole: false,
      ...(m.reasoning ? { thinkingFormat: "qwen-chat-template" } : {}),
    },
    input: m.vision ? ["text", "image"] : ["text"],
    cost: { input: 0, output: 0, cacheRead: 0, cacheWrite: 0 },
    contextWindow: m.contextWindow,
    maxTokens: m.maxTokens,
  };
}

export interface InstallResult {
  path: string;
  baseUrl: string;
  bakedModels: string[];
  serverReachable: boolean;
}

export async function installPiExtension(
  baseUrl: string = DEFAULT_BASE_URL,
  extensionsDir: string = defaultPiExtensionsDir(),
): Promise<InstallResult> {
  const models = await fetchServerModels(baseUrl);
  mkdirSync(extensionsDir, { recursive: true });
  const path = join(extensionsDir, PI_EXTENSION_FILENAME);
  writeFileSync(path, renderPiExtension(baseUrl, models));
  return { path, baseUrl, bakedModels: models.map((m) => m.id), serverReachable: models.length > 0 };
}

/** Returns true when a file was removed. */
export function removePiExtension(extensionsDir: string = defaultPiExtensionsDir()): boolean {
  const path = join(extensionsDir, PI_EXTENSION_FILENAME);
  if (!existsSync(path)) return false;
  rmSync(path);
  return true;
}
